### ISSUE TITLE
Storing files in server

### ISSUE THREAD

**Issue by ananthu2050** [jeroenooms/opencpu#143]
My opencpu app tries to stores some uploaded file in server. Except for /tmp/ocpu-temp my application is not able to read or write to any directory. I tried creating a folder with same privileges as /tmp/ocpu-temp

Permissions of /tmp/ocpu-temp
drwxr-xr-x 8 www-data www-data    12288 Apr 27 11:51 ocpu-temp

Permissions of /usr/local/ocpu (Folder I created to store uploaded files)
drwxr-xr-x  2 www-data www-data     4096 Apr 24 15:20 ocpu

When I tried to write this folder, I get permissions error. Any idea why this is happening? Is there any other location other than /tmp where I can store my app specific files. Eventually I want to store my sqllite db file too.

**Comment by jeroenooms** [comment]
Yes this is by design. You should store files in your working directory. That way they automatically get saved and you can retrieve them from the sesion url. For example:

    curl https://public.opencpu.org/ocpu/library/utils/R/write.csv -d "x=mtcars&file='mtcars.csv'"

If you really want to store files elsewhere on the server, you need to add this permission to the security profile by editing `/etc/apparmor.d/opencpu.d/custom` on the server. See also the [pdf manual](http://jeroenooms.github.com/opencpu-manual/opencpu-server.pdf) section about security.

**Comment by ananthu2050** [comment]
Thanks. It worked after editing /etc/apparmor.d/opencpu.d/custom and restarting apparmor service. I should have raised this question in google group. Sorry about posting it here.
