### ISSUE TITLE
openpcu-server uses older version of stringr which causes issues

### ISSUE THREAD

**Issue by moosilauke18** [jeroenooms/opencpu#145]
`stringr` just went through a major code change and now is version 1.0.0.  This causes issues if `stringr` is also used in a package.  When calling a function, this is displayed:

```
Package 'stringr' version 0.6.2 cannot be unloaded

In call:
library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc)
```

**Comment by jeroenooms** [comment]
Thanks for letting me know. This should only happen for packages that explicitly require `stringr > 0.6.2` right?

**Comment by moosilauke18** [comment]
It seems that if a you install a package via `devtools` onto the server that requires `stringr` regardless if it specifies a version it updates the version to `1.0.0`.

**Comment by ramvenkasocial** [comment]
I have the same issue with opencpu. It used to work before and kind of stuck. Any help is greatly appreciated.

**Comment by jeroenooms** [comment]
I have started publishing new builds based on R 3.2.0 to `opencpu-1.5`. Can you try switching to those?

```
sudo add-apt-repository opencpu/opencpu-1.5
sudo apt-get update
sudo apt-get dist-upgrade
```

**Comment by rubenarslan** [comment]
Possibly related:
I ran into trouble with stringi today (a stringr dependency). I saw you had the same issue on Solaris: https://github.com/Rexamine/stringi/issues/160

On Ubuntu, after updating to opencpu-1.5, I ran into this [ICU detection trouble](https://github.com/hadley/stringr/issues/68) too.
I re-installed stringi several times, but (related to the other issue from a few days back), opencpu was using the core stringi package from "/usr/lib/opencpu/library/stringi/libs". 
All my attempts to install ICU post-hoc failed, because I was trying to put it in `"/usr/local/lib/R/site-library/stringi/libs"`.

I solved it by calling `file.path(path.package("stringi"), "libs")` via openCPU's interface (not `sudo -i R`) and using that path with `sudo -i R`, i.e.

```r
library(stringi)
stri_install_icudt(check=F, outpath="/usr/lib/opencpu/library/stringi/libs")
```
This is already the second problem that I had trouble resolving because the packages called via `sudo -i  R` are different from those called via openCPU itself. Is there a method to call R from the command line with the same `.libPaths()` and attached packages? Would be useful, I think.

**Comment by jeroenooms** [comment]
I have been having trouble with stringi as well, i'm not so happy that this was pulled in as a required dependency for stringr (and hence devtools, knitr, etc). What error/problem exactly are you getting?

**Comment by rubenarslan** [comment]
I was getting "The requested ICU resource file cannot be found. Possible problem: ICU data has not been downloaded yet. Call stri_install_check(). (U_FILE_ACCESS_ERROR)"
but the above commands solved it, it's working now.

Can't speak to the faults or advantages of stringi, seems like a principled solution to all that funny string business in R.

**Comment by jeroenooms** [comment]
ICU is nice but stringi is a mess right now. I'll try to find some time to help them fix it.

**Comment by jeroenooms** [comment]
I have proposed a solution to the stringi authors, hopefully that will fix things: https://github.com/Rexamine/stringi/issues/162

**Comment by moosilauke18** [comment]
In the `opencpu/base` docker image the following is in the apache2 error log:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/lib/opencpu/library/stringi/libs/stringi.so':
  libicui18n.so.52: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘opencpu’
 From directive RHandler on line 12 of /etc/apache2/sites-enabled/opencpu.conf.
Setting locale to en_US.UTF-8
```

**Comment by jeroenooms** [comment]
@moosilauke18 hopefully [this](https://github.com/jeroenooms/opencpu-server/commit/7b25db6ce396b68a5dd3df6933912fd221f2e9bc) fixes it.
